### ISSUE TITLE
SAAS not compiling in WebSphere 8.5

### ISSUE THREAD

**Issue by jlcrow** [ic3fox/jawr-main-repo#17]
I've tried utilizing saas in version 3.8, I've added the vaadin-sass-compiler v0.9.12 to my project. Just as a simple test I added a test.scss file to my project with a $backcolor variable and then applied the variable to a body tag to change the color.  When I deploy to tomcat I see the color change, however when I point deploy the same project to WebSphere 8.5 I receive an unmodified file back from the jawr_generator.js.  I don't receive any exceptions, just a css file with unmodified variable strings.

**Comment by ic3fox** [comment]
Hi,

Do you get something correct in Production mode?
Do you have issue only on debug mode?

Cheers,

**Comment by jlcrow** [comment]
No, I get the raw text in the bundle, same issue as debug.

**Comment by ic3fox** [comment]
Hi

The ticket [JAWR-378](https://java.net/jira/browse/JAWR-378) has been created to track this issue.

Cheers

**Comment by jlcrow** [comment]
This was a missing dependency issue, flute-1.3.0.gg2.jar, sac-1.3.jar were needed in order for the vaadin compiler to work.  Sorry, my mistake.
