### ISSUE TITLE
External bundles not working in 3.8

### ISSUE THREAD

**Issue by havardge** [ic3fox/jawr-main-repo#19]
Hi,

I'm trying to set up an external bundle similar to the example on the website:

jawr.js.bundle.external.id=/bundles/externalBundle.js
jawr.js.bundle.external.debugURL=http://mycomp/js/foo.js
jawr.js.bundle.external.productionURL=http://mycomp/js/foo.min.js

**If I do specify a mapping I get**:

The bundle 'external', which use a static external resource in debug mode, can't have a bundle mapping.

**If I don't specify a mapping** I get a nullpointer in PropertiesBasedBundlesHandlerFactory#buildCustomBundleDefinition on this line:

StringTokenizer tk = new StringTokenizer(mappingsProperty, JawrConstant.COMMA_SEPARATOR);

Because the mappingsProperty is null, and then StringTokenizer throws a NullPointerException.

**Comment by ic3fox** [comment]
Hi,

You are right. There is an issue with external bundle.
The JIRA [JAWR-372](https://java.net/jira/browse/JAWR-372) has been created to track this issue.

Cheers,

**Comment by ic3fox** [comment]
This issue has been fixed in the master branch
