### ISSUE TITLE
JAWR Resource with parentheses in name won't load

### ISSUE THREAD

**Issue by jeremysnyder** [ic3fox/jawr-main-repo#21]
I am using an item from [WebJars](http://www.webjars.org/) in my `jawr.properties` file, and as odd as it may be, the file has `()` in the name, like so:

    webjars:/datatables-plugins/1.10.9/api/sum().js

When I add this file in, it is stripping out the parentheses, and this appears in my console log:

    Caused by: java.io.FileNotFoundException: META-INF/resources/webjars/datatables-plugins/1.10.9/api/sum.js could not be found. 
        at net.jawr.web.resource.bundle.factory.util.ClassLoaderResourceUtils.getResourceAsStream(ClassLoaderResourceUtils.java:111)
        at net.jawr.web.resource.bundle.generator.classpath.ClassPathGeneratorHelper.createStreamResource(ClassPathGeneratorHelper.java:73)

I tried escaping the parentheses with backslashes (`webjars:/datatables-plugins/1.10.9/api/sum\(\).js`), and it still didn't work.  After digging through the source code, I found that if I entered the reference in `jawr.properties` like this:

    webjars:/datatables-plugins/1.10.9/api/sum()().js

it worked just fine, due to the way it was searching for parentheses in the string.  I was happy to find a solution to this, but didn't feel it was documented, or maybe I missed the documentation on how parentheses are using in the `jawr.properties`.  Did I miss something here, should this case be added to the documentation, or should the code be updated to allow escaping of characters?

**Comment by ic3fox** [comment]
Hi

The parentheses have a particular meaning for resources associated with the generators. (it's used to give parameters to the generator for the resource creation)
I'll need to find a way to handle cleanly that case.
I'll open a issue in JIRA for that.

Thanks for reporting this case

Cheers,

**Comment by jeremysnyder** [comment]
Happy to.  Your project has been a big help to us, and I have really enjoyed using it.  

I did notice that our project was using Jawr 3.7, so I bumped to 3.8, and the issue is still there, but the message is a little different, just wanted to post it here for your reference:

    - 2016-01-22 08:38:37,659 [localhost-startStop-1] INFO  net.jawr.web.resource.handler.reader.ServletContextResourceReaderHandler - An exception occured while trying to read resource 'webjars:/datatables-plugins/1.10.9/api/sum().js'. Continuing with other readers. Error : null
    - 2016-01-22 08:38:37,659 [localhost-startStop-1] WARN  net.jawr.web.resource.bundle.handler.ResourceBundlesHandler - A mapped resource was not found: [webjars:/datatables-plugins/1.10.9/api/sum().js]. Please check your configuration
    - 2016-01-22 08:38:37,996 [localhost-startStop-1] INFO  net.jawr.web.resource.handler.reader.ServletContextResourceReaderHandler - An exception occured while trying to read resource 'webjars:/datatables-plugins/1.10.9/api/sum().js'. Continuing with other readers. Error : null
    - 2016-01-22 08:38:37,996 [localhost-startStop-1] WARN  net.jawr.web.resource.bundle.handler.ResourceBundlesHandler - A mapped resource was not found: [webjars:/datatables-plugins/1.10.9/api/sum().js]. Please check your configuration

**Comment by ic3fox** [comment]
Hi,

Thanks for your kind words :-)
I'm glad that it helps you.

The ticket [JAWR-376](https://java.net/jira/browse/JAWR-376) has been created to follow this issue.
You can follow the resolution of this issue on JIRA.

Cheers,

**Comment by ic3fox** [comment]
This issue has been fixed in the master branch
Thanks for the pull request with the unit tests, which was really helpful to fix this issue.

Cheers
