### ISSUE TITLE
mvn test error

### ISSUE THREAD

**Issue by neblina-software** [ic3fox/jawr-main-repo#22]
Hello, is there a way to successfully execute mvn test without errors?

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jawrJsController' defined in file [/Users/lastprophet/IdeaProjects/balerocms-enterprise/target/classes/com/neblina/balero/web/JawrJsController.class]: Invocation of init method failed; nested exception is java.lang.NullPointerException

If i execute
mvn spring-boot:run

it execute sucessfully.

I can't execute Unit Test

https://github.com/neblina-software/balerocms-enterprise

Im integratin jawr, regards!

**Comment by neblina-software** [comment]
p.s: test folder needed in spring-boot example!

**Comment by ic3fox** [comment]
Hi

I'll try to take a look at it this week end.

Cheers

**Comment by neblina-software** [comment]
@ic3fox app breaks when it calls JawrController in Unit Test, because web layer doesn't exists (I think). It shows an ServeletContext Exception.

**Comment by neblina-software** [comment]
@ic3fox finally i fix the problem.

ServletContext need to be atached in unit testing!

**Comment by ic3fox** [comment]
Great.

I'm glad that you've been able to fix this.
If you encounter other issues don't hesitate to send a message here.

Cheers,
