### ISSUE TITLE
JAWR 3.9 Release

### ISSUE THREAD

**Issue by mickske** [ic3fox/jawr-main-repo#32]
Hi,

when are you planning to release version 3.9, i saw that you have incorporated the JRuby sass compiler which could really com in handy for me since the vaadin compiler is very buggy and behind in feature set?

Thanks!

**Comment by ic3fox** [comment]
Hi mickske

I still have one feature which I would like to do properly before releasing the 3.9 version.
It's related to the caching mechanism of content produced by generators.

I don't have a lot of time right now.
So I will say that a rough estimation would be in a month, but as I'm doing this in my spare time, it's hard to be accurate.

Thanks for your interest to this project.

**Comment by mickske** [comment]
Okay cool, thanks for the indication at least :)

Keep up the good work! 👍

**Comment by ic3fox** [comment]
Hi,

The version 3.9 of Jawr has been released.
You'll find more information on the Jawr web site.

Cheers,
