### ISSUE TITLE
Basic analog for jawr.[type].bundle.[name].bundle.prefix

### ISSUE THREAD

**Issue by mryabets** [ic3fox/jawr-main-repo#35]
From [documentation](https://jawr.java.net/docs/descriptor_syntax.html#JSCSS_bundle_definition_properties):

> jawr.[type].bundle.[name].bundle.prefix
... This can be helpful to define security filters to access bundles.

But what if I want to define filter for all bundles and **orphans**?
I don't see analogous basic property that doesn't override context path.

**Comment by ic3fox** [comment]
Hi,

It is possible to define a prefix for all bundles including orphans using the mapping property of the servlet.

Something like : 
`...
        <servlet>
                <servlet-name>JavascriptServlet</servlet-name>
                <servlet-class>net.jawr.web.servlet.JawrServlet</servlet-class>
                <init-param>
                        <param-name>configLocation</param-name>
                        <param-value>/jawr.properties</param-value>
                </init-param>
                <init-param>
                        <param-name>mapping</param-name>
                        <param-value>/jsJawrPath/</param-value>
                </init-param>
                <load-on-startup>1</load-on-startup>
        </servlet>
        ...
        
        <servlet-mapping>
                <servlet-name>JavascriptServlet</servlet-name>
                <url-pattern>/jsJawrPath/*</url-pattern>
        </servlet-mapping> 
`

Please check the [documentation](https://jawr.java.net/docs/servlet.html) for more detail

Is it what you were looking for?

Cheers

**Comment by mryabets** [comment]
I just didn't set mapping in JawrSpringController.
Now it's working fine.
Thank you.

**Comment by ic3fox** [comment]
You're welcome :-)
