### ISSUE TITLE
Maven Central Missing 3.7 jar Artifact

### ISSUE THREAD

**Issue by Pytry** [ic3fox/jawr-main-repo#8]
The latest deployment to maven central (last Saterday, 05/23/2015) seems to have left out the *.jar artifact from the deployment.
The pom files are present.
This is causing a build error for us, since we (unfortunately) have a dependancy on a 3rd party api that has a build dependency on "the latest" version of jawr, instead of a specific version. 
This code is out of our hands at the moment, so it would be great if the latest version of the jawr-*.jar could get deployed to maven central.

Dependency:

    <dependency> 
        <groupId>net.jawr</groupId> 
        <artifactId>jawr</artifactId> 
        <version>[3,]</version> 
        <optional>true</optional> 
    </dependency>

**Comment by Pytry** [comment]
There are actually two places in this 3rd party API that have dependencies on "the latest" version. Here's the other sample:

    <dependency> 
        <groupId>net.jawr</groupId> 
        <artifactId>jawr</artifactId> 
        <version>[3,]</version>  
    </dependency> 

Notice that this second one lacks the 
"optional" tag.

**Comment by ic3fox** [comment]
Hi,

The jawr library has been renamed as jawr-core snce the version 3.5.

So your dependency declaration should look like this :

<dependency>
    <groupId>net.jawr</groupId>
    <artifactId>jawr-core</artifactId>
    <version>[3,]</version>
</dependency>

**Comment by Pytry** [comment]
We will have to update our dependencies .. eventually (funding .. lots of project dependencies etc).
I also plan on adding a specific version dependency when we do.
We were able to overcome this problem by excluding the jawr api from the 3rd party dependency, and instead including it explicitly in our own pom.xml.

However, there is a jawr 3.7 version folder in Maven Central that was added last Saturday. Here's a link to it: 

    http://search.maven.org/#browse%7C-1134876859

Perhaps the problem is not that it's missing the jar, but that none of those files should have been added in the first place?

**Comment by ic3fox** [comment]
Hi

I'm glad that you've been able to fix your issue.
The pom referenced with net.jawr:jawr:3.7 is a parent pom.
It is normal that it has been published.

Please warn this 3rd party api that there using a wrong dependency declaration or let me know I'll try to contact them.

Cheers,
