### ISSUE TITLE
Use a deterministic parameter instead of a random value for debug urls.

### ISSUE THREAD

**Issue by safetytrick** [ic3fox/jawr-main-repo#9]
jawr.debug.use.random.parameter adds a random value to urls, using a value computed from the hash of the content or the last modified time would help in development to preserve breakpoints while still keeping content up to date.

**Comment by ic3fox** [comment]
Hi

We could use the last modified time but I'm not sure that this attribute is properly kept during war deployment, and for the use of both (last modified date + the hash of the content), this could slow down the generation of the URL a little bit.

When developing, I generally set this parameter to false and disable cache in my browser.
Would this workaround fix your issue?

Cheers,

**Comment by michaelnielson-taulia** [comment]
Either method would definitely slow down generation of the URL and there are certainly workarounds. This is definitely a feature request and if I really want it I should probably take a hack at it myself :)

The source of my irritation comes from the way the grails plugin and tag lib for <jawr:script /> default to useRandomParam whenever debug mode is on, you must explicitly turn it off at the script level (it never actually looks at this property: jawr.debug.use.random.parameter)

See: https://github.com/ic3fox/jawr-main-repo/blob/fbc3157cdb3de990d7e7ae0b42d88953065577e1/jawr-grails/jawr-grails-plugin/grails-app/taglib/JawrTagLib.groovy

**Comment by ic3fox** [comment]
Hi

The fact that the property *jawr.debug.use.random.parameter* is not properly handled in the jawrTagLib is an issue.

The JIRA [JAWR-338!](https://java.net/jira/browse/JAWR-338) has been created to fix this issue.

Cheers

**Comment by michaelnielson-taulia** [comment]
Thank you!

**Comment by ic3fox** [comment]
Hi,

This issue has been fixed in the master branch.
This fix will be part of the next release.

Cheers,

**Comment by michaelnielson-taulia** [comment]
That's some seriously fast turn around, thank you!
