### ISSUE TITLE
Integration with Spring MVC 4x or later

### ISSUE THREAD

**Issue by ns-bruno** [ic3fox/jawr-main-repo#90]
In the documentation it is written that can only be integrated with Spring 2.x, but nowadays the Spring MVC is already in version 5.x, so my question is:
JAWR integration with Spring MVC is able to integrate with version 5.x?

Another question, have time that does not have a jawr update, so will they discontinue or will we have new updates?

**Comment by pthorson** [comment]
The pom compiles in 4:
<spring.version>4.1.2.RELEASE</spring.version>

Some incompatibility with Spring Boot 2 was also recently fixed in #81
